//Code Type
export const PRIORITYTYPE = "PriorityType"
export const EMPLOYEECATEGORY = "EmployeeCategory"
export const LEAVETYPE = "LeaveType"
export const PROJECTTECHSTACKCATAGORY = "ProjectTechStackCatagory"
export const PROJECTTYPE = "ProjectType"
export const ROLE = "Role"
export const TASKCLASSIFICATION = "TaskClassification"
export const TASKTYPE = "TaskType"
export const UICATEGORY = "UICategory"

//Code Name
export const NET = ".Net"
export const BUSINESSANALYST = "BusinessAnalyst"
export const CSHARP = "C#"
export const CUSTOMER = "Customer"
export const DEVELOPMENT = "Development"
export const DIGITALMARKETING = "DigitalMarketing"
export const HR = "HR"
export const LEAVESUBTYPE = "LeaveSubType"
export const MANAGEMENT = "Management"
export const MVC = "MVC"
export const NONE = "None"
export const OTHER = "Other"
export const OTHERS = "Others"
export const QUADRANT = "Quadrant"
export const REACTJS = "ReactJs"
export const SALES = "Sales"
export const SEARCH_ASSIGN = "Search & Assign"
export const SEARCH_LIST = "Search List"
export const SEARCH_LIST_ADD_EDIT = "Search List,Add,Edit"
export const SEARCH_LIST_ADD_EDIT_VIEW = "Search List,Add,Edit,View"
export const SEARCH_LIST_ASSIGN = "Search List,Assign"
export const WEBAPI =" WebAPI"