import { TaskDTO } from "../../Models/Task/Task";
import { TaskFilter } from "../../Models/Task/TaskFilter";
import { ConvertToISO, WeekEndingDate } from "../../Utilities/Utils";

export const FILTER: TaskFilter = {
  name: null,
  projectName: null,
  status: null,
  percentage: null,
  category: null,
  subCategory: null,
  actualTime: null,
  estimatedTime: null,
  estStartDate: null,
  estEndDate: null,
  actStartDate: null,
  actEndDate: null,
  taskName: null,
  startDate: null,
  endDate: null,
  priority: null,
  weekEndingDate: null,
  projectType: null,
  teamName: null,
  employeeName: null,
}

export const TASK: TaskDTO = {
  uiUserStoryId: null,
  id: 0,
  employeeTaskId: 0,
  projectId: 0,
  teamId: 0,
  categoryId: 0,
  uiId: 0,
  userStoryId: 0,
  name: "",
  description: "",
  actualStartDate: new Date("0001-01-01 00:00:00.0000000"),
  actualEndDate: new Date("0001-01-01 00:00:00.0000000"),
  estTime:"",
  actTime: null,
  weekEndingDate: ConvertToISO(WeekEndingDate()),
  status: "Unassigned",
  priority: "",
  percentage: 0,
  estimateStartDate: "",
  estimateEndDate: "",
  taskType: "",
  classification: "",
  comment: "",
  comments: [],
  employeeId: 0,
  taskDescription: null,
  userStoryUIId: 0,
  createdDate: null,
  createdBy: "user",
  updatedDate: null,
  employeeName: null,
  updatedBy: "user",
  completedTaskCount: null,
  inProgressTaskCount: null,
};


